name: pharynphoto
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.7
  - pytorch=1.8.0
  - torchvision=0.9.0
  - pytorch-cuda
  - cudatoolkit=10.2
  - albumentations
  - tqdm
  - matplotlib
  - numpy
  # - pip:
    # - albumentations  # slightly more up to date
